spring:
  datasource:
    url: jdbc:h2:mem:students
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  jpa:
    defer-datasource-initialization: false
    show-sql: true
  h2:
    console:
      enabled: true
      path: /db-students
